/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoDemoRouteImport } from './routes/video-demo'
import { Route as VideDemoRouteImport } from './routes/vide-demo'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PitchDeckRouteImport } from './routes/pitch-deck'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as LegacyRouteImport } from './routes/legacy'
import { Route as IsolatedMarketsRouteImport } from './routes/isolated-markets'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as FaucetRouteImport } from './routes/faucet'
import { Route as EarnRouteImport } from './routes/earn'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioChainProtocolPositionIdRouteImport } from './routes/portfolio_.$chain.$protocol.$positionId'
import { Route as MarketsChainProtocolMarketIdRouteImport } from './routes/markets_.$chain.$protocol.$marketId'

const VideoDemoRoute = VideoDemoRouteImport.update({
  id: '/video-demo',
  path: '/video-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const VideDemoRoute = VideDemoRouteImport.update({
  id: '/vide-demo',
  path: '/vide-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchDeckRoute = PitchDeckRouteImport.update({
  id: '/pitch-deck',
  path: '/pitch-deck',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyRoute = LegacyRouteImport.update({
  id: '/legacy',
  path: '/legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IsolatedMarketsRoute = IsolatedMarketsRouteImport.update({
  id: '/isolated-markets',
  path: '/isolated-markets',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const FaucetRoute = FaucetRouteImport.update({
  id: '/faucet',
  path: '/faucet',
  getParentRoute: () => rootRouteImport,
} as any)
const EarnRoute = EarnRouteImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioChainProtocolPositionIdRoute =
  PortfolioChainProtocolPositionIdRouteImport.update({
    id: '/portfolio_/$chain/$protocol/$positionId',
    path: '/portfolio/$chain/$protocol/$positionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MarketsChainProtocolMarketIdRoute =
  MarketsChainProtocolMarketIdRouteImport.update({
    id: '/markets_/$chain/$protocol/$marketId',
    path: '/markets/$chain/$protocol/$marketId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/brand': typeof BrandRoute
  '/dashboard': typeof DashboardRoute
  '/design-system': typeof DesignSystemRoute
  '/docs': typeof DocsRoute
  '/earn': typeof EarnRoute
  '/faucet': typeof FaucetRoute
  '/governance': typeof GovernanceRoute
  '/isolated-markets': typeof IsolatedMarketsRoute
  '/legacy': typeof LegacyRoute
  '/markets': typeof MarketsRoute
  '/pitch-deck': typeof PitchDeckRoute
  '/portfolio': typeof PortfolioRoute
  '/referrals': typeof ReferralsRoute
  '/settings': typeof SettingsRoute
  '/trade': typeof TradeRoute
  '/vide-demo': typeof VideDemoRoute
  '/video-demo': typeof VideoDemoRoute
  '/markets/$chain/$protocol/$marketId': typeof MarketsChainProtocolMarketIdRoute
  '/portfolio/$chain/$protocol/$positionId': typeof PortfolioChainProtocolPositionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/brand': typeof BrandRoute
  '/dashboard': typeof DashboardRoute
  '/design-system': typeof DesignSystemRoute
  '/docs': typeof DocsRoute
  '/earn': typeof EarnRoute
  '/faucet': typeof FaucetRoute
  '/governance': typeof GovernanceRoute
  '/isolated-markets': typeof IsolatedMarketsRoute
  '/legacy': typeof LegacyRoute
  '/markets': typeof MarketsRoute
  '/pitch-deck': typeof PitchDeckRoute
  '/portfolio': typeof PortfolioRoute
  '/referrals': typeof ReferralsRoute
  '/settings': typeof SettingsRoute
  '/trade': typeof TradeRoute
  '/vide-demo': typeof VideDemoRoute
  '/video-demo': typeof VideoDemoRoute
  '/markets/$chain/$protocol/$marketId': typeof MarketsChainProtocolMarketIdRoute
  '/portfolio/$chain/$protocol/$positionId': typeof PortfolioChainProtocolPositionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/brand': typeof BrandRoute
  '/dashboard': typeof DashboardRoute
  '/design-system': typeof DesignSystemRoute
  '/docs': typeof DocsRoute
  '/earn': typeof EarnRoute
  '/faucet': typeof FaucetRoute
  '/governance': typeof GovernanceRoute
  '/isolated-markets': typeof IsolatedMarketsRoute
  '/legacy': typeof LegacyRoute
  '/markets': typeof MarketsRoute
  '/pitch-deck': typeof PitchDeckRoute
  '/portfolio': typeof PortfolioRoute
  '/referrals': typeof ReferralsRoute
  '/settings': typeof SettingsRoute
  '/trade': typeof TradeRoute
  '/vide-demo': typeof VideDemoRoute
  '/video-demo': typeof VideoDemoRoute
  '/markets_/$chain/$protocol/$marketId': typeof MarketsChainProtocolMarketIdRoute
  '/portfolio_/$chain/$protocol/$positionId': typeof PortfolioChainProtocolPositionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/analytics'
    | '/brand'
    | '/dashboard'
    | '/design-system'
    | '/docs'
    | '/earn'
    | '/faucet'
    | '/governance'
    | '/isolated-markets'
    | '/legacy'
    | '/markets'
    | '/pitch-deck'
    | '/portfolio'
    | '/referrals'
    | '/settings'
    | '/trade'
    | '/vide-demo'
    | '/video-demo'
    | '/markets/$chain/$protocol/$marketId'
    | '/portfolio/$chain/$protocol/$positionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/analytics'
    | '/brand'
    | '/dashboard'
    | '/design-system'
    | '/docs'
    | '/earn'
    | '/faucet'
    | '/governance'
    | '/isolated-markets'
    | '/legacy'
    | '/markets'
    | '/pitch-deck'
    | '/portfolio'
    | '/referrals'
    | '/settings'
    | '/trade'
    | '/vide-demo'
    | '/video-demo'
    | '/markets/$chain/$protocol/$marketId'
    | '/portfolio/$chain/$protocol/$positionId'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/analytics'
    | '/brand'
    | '/dashboard'
    | '/design-system'
    | '/docs'
    | '/earn'
    | '/faucet'
    | '/governance'
    | '/isolated-markets'
    | '/legacy'
    | '/markets'
    | '/pitch-deck'
    | '/portfolio'
    | '/referrals'
    | '/settings'
    | '/trade'
    | '/vide-demo'
    | '/video-demo'
    | '/markets_/$chain/$protocol/$marketId'
    | '/portfolio_/$chain/$protocol/$positionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BrandRoute: typeof BrandRoute
  DashboardRoute: typeof DashboardRoute
  DesignSystemRoute: typeof DesignSystemRoute
  DocsRoute: typeof DocsRoute
  EarnRoute: typeof EarnRoute
  FaucetRoute: typeof FaucetRoute
  GovernanceRoute: typeof GovernanceRoute
  IsolatedMarketsRoute: typeof IsolatedMarketsRoute
  LegacyRoute: typeof LegacyRoute
  MarketsRoute: typeof MarketsRoute
  PitchDeckRoute: typeof PitchDeckRoute
  PortfolioRoute: typeof PortfolioRoute
  ReferralsRoute: typeof ReferralsRoute
  SettingsRoute: typeof SettingsRoute
  TradeRoute: typeof TradeRoute
  VideDemoRoute: typeof VideDemoRoute
  VideoDemoRoute: typeof VideoDemoRoute
  MarketsChainProtocolMarketIdRoute: typeof MarketsChainProtocolMarketIdRoute
  PortfolioChainProtocolPositionIdRoute: typeof PortfolioChainProtocolPositionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video-demo': {
      id: '/video-demo'
      path: '/video-demo'
      fullPath: '/video-demo'
      preLoaderRoute: typeof VideoDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vide-demo': {
      id: '/vide-demo'
      path: '/vide-demo'
      fullPath: '/vide-demo'
      preLoaderRoute: typeof VideDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitch-deck': {
      id: '/pitch-deck'
      path: '/pitch-deck'
      fullPath: '/pitch-deck'
      preLoaderRoute: typeof PitchDeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy': {
      id: '/legacy'
      path: '/legacy'
      fullPath: '/legacy'
      preLoaderRoute: typeof LegacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/isolated-markets': {
      id: '/isolated-markets'
      path: '/isolated-markets'
      fullPath: '/isolated-markets'
      preLoaderRoute: typeof IsolatedMarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faucet': {
      id: '/faucet'
      path: '/faucet'
      fullPath: '/faucet'
      preLoaderRoute: typeof FaucetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earn': {
      id: '/earn'
      path: '/earn'
      fullPath: '/earn'
      preLoaderRoute: typeof EarnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio_/$chain/$protocol/$positionId': {
      id: '/portfolio_/$chain/$protocol/$positionId'
      path: '/portfolio/$chain/$protocol/$positionId'
      fullPath: '/portfolio/$chain/$protocol/$positionId'
      preLoaderRoute: typeof PortfolioChainProtocolPositionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets_/$chain/$protocol/$marketId': {
      id: '/markets_/$chain/$protocol/$marketId'
      path: '/markets/$chain/$protocol/$marketId'
      fullPath: '/markets/$chain/$protocol/$marketId'
      preLoaderRoute: typeof MarketsChainProtocolMarketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AnalyticsRoute: AnalyticsRoute,
  BrandRoute: BrandRoute,
  DashboardRoute: DashboardRoute,
  DesignSystemRoute: DesignSystemRoute,
  DocsRoute: DocsRoute,
  EarnRoute: EarnRoute,
  FaucetRoute: FaucetRoute,
  GovernanceRoute: GovernanceRoute,
  IsolatedMarketsRoute: IsolatedMarketsRoute,
  LegacyRoute: LegacyRoute,
  MarketsRoute: MarketsRoute,
  PitchDeckRoute: PitchDeckRoute,
  PortfolioRoute: PortfolioRoute,
  ReferralsRoute: ReferralsRoute,
  SettingsRoute: SettingsRoute,
  TradeRoute: TradeRoute,
  VideDemoRoute: VideDemoRoute,
  VideoDemoRoute: VideoDemoRoute,
  MarketsChainProtocolMarketIdRoute: MarketsChainProtocolMarketIdRoute,
  PortfolioChainProtocolPositionIdRoute: PortfolioChainProtocolPositionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
