/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PitchDeckRouteImport } from './routes/pitch-deck'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as IsolatedMarketsRouteImport } from './routes/isolated-markets'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as FaucetRouteImport } from './routes/faucet'
import { Route as EarnRouteImport } from './routes/earn'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchDeckRoute = PitchDeckRouteImport.update({
  id: '/pitch-deck',
  path: '/pitch-deck',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const IsolatedMarketsRoute = IsolatedMarketsRouteImport.update({
  id: '/isolated-markets',
  path: '/isolated-markets',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const FaucetRoute = FaucetRouteImport.update({
  id: '/faucet',
  path: '/faucet',
  getParentRoute: () => rootRouteImport,
} as any)
const EarnRoute = EarnRouteImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/brand': typeof BrandRoute
  '/dashboard': typeof DashboardRoute
  '/earn': typeof EarnRoute
  '/faucet': typeof FaucetRoute
  '/governance': typeof GovernanceRoute
  '/isolated-markets': typeof IsolatedMarketsRoute
  '/markets': typeof MarketsRoute
  '/pitch-deck': typeof PitchDeckRoute
  '/portfolio': typeof PortfolioRoute
  '/referrals': typeof ReferralsRoute
  '/settings': typeof SettingsRoute
  '/trade': typeof TradeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/brand': typeof BrandRoute
  '/dashboard': typeof DashboardRoute
  '/earn': typeof EarnRoute
  '/faucet': typeof FaucetRoute
  '/governance': typeof GovernanceRoute
  '/isolated-markets': typeof IsolatedMarketsRoute
  '/markets': typeof MarketsRoute
  '/pitch-deck': typeof PitchDeckRoute
  '/portfolio': typeof PortfolioRoute
  '/referrals': typeof ReferralsRoute
  '/settings': typeof SettingsRoute
  '/trade': typeof TradeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/brand': typeof BrandRoute
  '/dashboard': typeof DashboardRoute
  '/earn': typeof EarnRoute
  '/faucet': typeof FaucetRoute
  '/governance': typeof GovernanceRoute
  '/isolated-markets': typeof IsolatedMarketsRoute
  '/markets': typeof MarketsRoute
  '/pitch-deck': typeof PitchDeckRoute
  '/portfolio': typeof PortfolioRoute
  '/referrals': typeof ReferralsRoute
  '/settings': typeof SettingsRoute
  '/trade': typeof TradeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/brand'
    | '/dashboard'
    | '/earn'
    | '/faucet'
    | '/governance'
    | '/isolated-markets'
    | '/markets'
    | '/pitch-deck'
    | '/portfolio'
    | '/referrals'
    | '/settings'
    | '/trade'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/brand'
    | '/dashboard'
    | '/earn'
    | '/faucet'
    | '/governance'
    | '/isolated-markets'
    | '/markets'
    | '/pitch-deck'
    | '/portfolio'
    | '/referrals'
    | '/settings'
    | '/trade'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/brand'
    | '/dashboard'
    | '/earn'
    | '/faucet'
    | '/governance'
    | '/isolated-markets'
    | '/markets'
    | '/pitch-deck'
    | '/portfolio'
    | '/referrals'
    | '/settings'
    | '/trade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BrandRoute: typeof BrandRoute
  DashboardRoute: typeof DashboardRoute
  EarnRoute: typeof EarnRoute
  FaucetRoute: typeof FaucetRoute
  GovernanceRoute: typeof GovernanceRoute
  IsolatedMarketsRoute: typeof IsolatedMarketsRoute
  MarketsRoute: typeof MarketsRoute
  PitchDeckRoute: typeof PitchDeckRoute
  PortfolioRoute: typeof PortfolioRoute
  ReferralsRoute: typeof ReferralsRoute
  SettingsRoute: typeof SettingsRoute
  TradeRoute: typeof TradeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitch-deck': {
      id: '/pitch-deck'
      path: '/pitch-deck'
      fullPath: '/pitch-deck'
      preLoaderRoute: typeof PitchDeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/isolated-markets': {
      id: '/isolated-markets'
      path: '/isolated-markets'
      fullPath: '/isolated-markets'
      preLoaderRoute: typeof IsolatedMarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faucet': {
      id: '/faucet'
      path: '/faucet'
      fullPath: '/faucet'
      preLoaderRoute: typeof FaucetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earn': {
      id: '/earn'
      path: '/earn'
      fullPath: '/earn'
      preLoaderRoute: typeof EarnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BrandRoute: BrandRoute,
  DashboardRoute: DashboardRoute,
  EarnRoute: EarnRoute,
  FaucetRoute: FaucetRoute,
  GovernanceRoute: GovernanceRoute,
  IsolatedMarketsRoute: IsolatedMarketsRoute,
  MarketsRoute: MarketsRoute,
  PitchDeckRoute: PitchDeckRoute,
  PortfolioRoute: PortfolioRoute,
  ReferralsRoute: ReferralsRoute,
  SettingsRoute: SettingsRoute,
  TradeRoute: TradeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
